### ISSUE TITLE
Use Jimp in Browser with webpack build

### ISSUE THREAD

**Issue by huytran0605** [oliver-moran/jimp#376]
I'm facing a lot of issues when trying to use Jimp on browser with webpack build.
I tried to used browser version by `import Jimp from 'jimp/browser/lib/jimp';`
But it didn't work and i got error ` _jimp2.default.read is not a function`
Could you please help me to solve that? Because i used Jimp on node server and it worked perfectly. So I really want to use Jimp in Browser.

**Comment by steffkelsey** [comment]
If you're pulling from npm, the 0.2.28 version is completely broken for browser. I ended up grabbing version 0.2.27 and then my import statement looked like this:
`import 'jimp/browser/lib/jimp';` and everything worked fine from there (can just call `Jimp.read(...)`)

**Comment by hugomallet** [comment]
Any update ? Still impossible to use this module in the browser....

**Comment by hipstersmoothie** [comment]
this is working in latest master (not 0.2.28). see my issue #466. Jimp is attached to the window instead of working with require. closing in favor of #466 

also you shouldn't need to import 'jimp/browser/lib/jimp' as webpack will do this for you. I have a sample repo I can push if you want to see a minimal working webpack build.

**Comment by niccih** [comment]
I would be very interested in seeing your sample repo, with the minimal working webpack build - tia,

**Comment by hipstersmoothie** [comment]
@niccih https://github.com/hipstersmoothie/jimp-example let me know if you have any problems!
